trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
  - name: targetFolder
    value: ''  # This variable will be set dynamically based on the changed folder
  - name: pythonVersion
    value: ''
  - name: qaPath
    value: ''

jobs:
- job: SetTargetFolder
  displayName: 'Detect Changed Folder'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    persistCredentials: true
    clean: true
    displayName: "Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)"
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Fetch all the branches and tags to ensure we have the commit in history
        git log -1 --oneline --name-only
        #git whatchanged